# Generated by Django 5.2.4 on 2025-07-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_requests', '0003_workflowfileanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowfileanalysis',
            name='workflow_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workflowfileanalysis',
            name='workflow_file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
