# Generated by Django 5.2.4 on 2025-07-31 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome identificativo della connessione', max_length=100)),
                ('host', models.CharField(help_text='Hostname o IP del server', max_length=255)),
                ('port', models.IntegerField(default=22, help_text='Porta SSH')),
                ('username', models.CharField(help_text='Username per la connessione', max_length=100)),
                ('password', models.CharField(blank=True, help_text='Password (opzionale se si usa chiave)', max_length=255)),
                ('private_key_path', models.CharField(blank=True, help_text='Path alla chiave privata', max_length=500)),
                ('remote_base_path', models.CharField(default='/app/workflows', help_text='Path base remoto dove salvare i file', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SSH Connection',
                'verbose_name_plural': 'SSH Connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_file_path', models.CharField(help_text='Path locale del file', max_length=1000)),
                ('remote_file_path', models.CharField(help_text='Path remoto dove salvare il file', max_length=1000)),
                ('file_name', models.CharField(help_text='Nome del file', max_length=255)),
                ('file_content', models.TextField(help_text='Contenuto del file da deployare')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Messaggio di errore se il deployment fallisce')),
                ('workflow_id', models.UUIDField(blank=True, help_text='ID del workflow associato', null=True)),
                ('deployment_notes', models.TextField(blank=True, help_text='Note aggiuntive sul deployment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_deployments', to=settings.AUTH_USER_MODEL)),
                ('ssh_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='ssh_deployment.sshconnection')),
            ],
            options={
                'verbose_name': 'File Deployment',
                'verbose_name_plural': 'File Deployments',
                'ordering': ['-created_at'],
            },
        ),
    ]
